link:
	rm -fr ./node_modules/@utilitywarehouse/customer-tracking-core
	rm -fr ./node_modules/@utilitywarehouse/customer-tracking-for-server
	rm -fr ./node_modules/@utilitywarehouse/customer-tracking-types
	ln -s ../../../../../js/packages/core ./node_modules/@utilitywarehouse/customer-tracking-core
	ln -s ../../../../../js/packages/for-server ./node_modules/@utilitywarehouse/customer-tracking-for-server
	ln -s ../../../../../js/packages/types ./node_modules/@utilitywarehouse/customer-tracking-types