link:
	rm -fr ./node_modules/@utilitywarehouse/customer-tracking-core
	rm -fr ./node_modules/@utilitywarehouse/customer-tracking-for-browser
	rm -fr ./node_modules/@utilitywarehouse/customer-tracking-types
	ln -s ../../../../../js/packages/core ./node_modules/@utilitywarehouse/customer-tracking-core
	ln -s ../../../../../js/packages/for-browser ./node_modules/@utilitywarehouse/customer-tracking-for-browser
	ln -s ../../../../../js/packages/types ./node_modules/@utilitywarehouse/customer-tracking-types